#!/bin/bash

MODE=$1 && shift
NAME=$1 && shift
SITE=$1 && shift
REGISTRY=$1 && shift
TAG=$1 && shift
OWNER_UID=$1 && shift
OWNER_GID=$1 && shift
ENV=$1 && shift

create_dir "$SITE/logs" $OWNER_UID $OWNER_GID

docker run $MODE \
  -h $(hostname -f) \
  --name ${NAME} \
  -p 8082:8080 \
  -p 29418:29418 \
  -v $SITE/etc:/var/gerrit/etc \
  -v $SITE/git:/var/gerrit/git \
  -v $SITE/logs:/var/gerrit/logs \
  -v $SITE/lib:/var/gerrit/lib \
  $ENV \
  ${REGISTRY}k8sgerrit/${NAME}:${TAG}
