apiVersion: "gerritoperator.google.com/v1alpha3"
kind: GerritCluster
metadata:
  name: gerrit
spec:
  storage:
    storageClasses:
      readWriteOnce: default
      readWriteMany: nfs-client
    gitRepositoryStorage:
      size: 1Gi
    logsStorage:
      size: 1Gi
  ingress:
    enabled: true
    host: example.com
    tls:
      enabled: false
  gerrits:
  - metadata:
      name: gerrit
    spec:
      site:
        size: 5Gi
      plugins: []
      configFiles:
        gerrit.config: |-
          [auth]
            type = DEVELOPMENT_BECOME_ANY_ACCOUNT
          [container]
            javaOptions = -Xms200m
            javaOptions = -Xmx4g
          [gerrit]
            serverId = gerrit-1
          [transfer]
            timeout = 120 s
          [user]
            name = Gerrit Code Review
            email = gerrit@example.com
            anonymousCoward = Unnamed User
      secrets:
      - gerrit-secure-config
  receiver:
    metadata:
      name: receiver
    spec:
      credentialSecretRef: receiver-credentials
