apiVersion: "gerritoperator.google.com/v1alpha1"
kind: GerritCluster
metadata:
  name: gerrit
spec:
  storageClasses:
    readWriteOnce: default
    readWriteMany: nfs-client
  gitRepositoryStorage:
    size: 1Gi
  gerritLogsStorage:
    size: 1Gi
