apiVersion: "gerritoperator.google.com/v1alpha2"
kind: Receiver
metadata:
  name: receiver
spec:
  cluster: gerrit
  credentialSecretRef: receiver-htpasswd
---
apiVersion: v1
kind: Secret
metadata:
  name:  receiver-htpasswd
  labels:
    app: gerrit
data:
  .htpasswd: Z2l0OiRhcHIxJE8vTGJMS0M3JFE2MEdXRTdPY3FTRU1TZmUvSzh4VS4=
type: Opaque
