---
apiVersion: v1
kind: Secret
metadata:
  name:  gerrit-secure-config
  namespace: gerrit
  labels:
    app: gerrit
data:
  ssh_host_ecdsa_key: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFhQUFBQUJObFkyUnpZUwoxemFHRXlMVzVwYzNSd01qVTJBQUFBQ0c1cGMzUndNalUyQUFBQVFRUmNZWUNCZnVxczd3d2Q2amN5a0J4NXZ0QjRrSkp2CmxtbnlMS2EwbEZ1L1BpbVNUbmdUcXBRM3d5bHFsWEtLZ2ZsbzJyWkQzRCtkZGRFNUNxRXBTZDVOQUFBQXNFUGsvY0ZENVAKM0JBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF5TlRZQUFBQUlibWx6ZEhBeU5UWUFBQUJCQkZ4aGdJRis2cXp2REIzcQpOektRSEhtKzBIaVFrbStXYWZJc3ByU1VXNzgrS1pKT2VCT3FsRGZES1dxVmNvcUIrV2phdGtQY1A1MTEwVGtLb1NsSjNrCjBBQUFBaEFLZC9IY3g4RlZkM3JPQ2J4ODFmWUxYeGFKOWc2dk1QWXRNdUFRb3E2YkI0QUFBQUVXczRjMmRsY25KcGRDMWwKZUdGdGNHeGxBUUlEQkFVRwotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0=
  ssh_host_ecdsa_key.pub: |
    ZWNkc2Etc2hhMi1uaXN0cDI1NiBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF5TlRZQUFBQUlibWx6ZEhBeU5UWUFBQUJCQkZ4aGdJRis2cXp2REIzcU56S1FISG0rMEhpUWttK1dhZklzcHJTVVc3OCtLWkpPZUJPcWxEZkRLV3FWY29xQitXamF0a1BjUDUxMTBUa0tvU2xKM2swPSBrOHNnZXJyaXQtZXhhbXBsZQ==
  secure.config: |
    W2F1dGhdCglyZWdpc3RlckVtYWlsUHJpdmF0ZUtleSA9IEEzRDAwTnkwYkxXMno3eGRJbnZJZjM1UTVtRENpNXU5by9FPQoJYmVhcmVydG9rZW4gPSBzb21lLWJlYXJlci10b2tlbgo=
type: Opaque

---
apiVersion: "gerritoperator.google.com/v1beta10"
kind: GerritCluster
metadata:
  name: gerrit
  namespace: gerrit
spec:
  eventsBroker:
    brokerType: KAFKA
    eventsKafkaConfig:
      kafkaProperties:
          bootstrapServers: "kafka-service.kafka-zk.svc.cluster.local:9092"
          securityProtocol: "PLAINTEXT"
          enableAutoCommit: "true"
          autoCommitIntervalMs: "1000"
          autoOffsetReset: "latest"
      pluginProperties:
          sendStreamEvents: "true"
  storage:
    storageClasses:
      readWriteOnce: standard

  ingress:
    enabled: true
    host: gerrit.multisite.com
    annotations: {}
    tls:
      enabled: false
      secret: "gerrit-multisite-credential"
    ssh:
      enabled: true
    istio:
      gatewaySelector:
        istio: ingressgateway

  serverId: "minikube-gerrit"

  fluentBitSidecar:
    enabled: true

  gerrits:
  - metadata:
      name: gerrit
      labels:
        app: gerrit
    spec:
      serviceAccount: gerrit

      replicas: 3

      resources:
        requests:
          cpu: 1
          memory: 5Gi
        limits:
          cpu: 1
          memory: 6Gi

      startupProbe:
        initialDelaySeconds: 120
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3

      readinessProbe:
        initialDelaySeconds: 120
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3

      livenessProbe:
        initialDelaySeconds: 120
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3

      service:
        type: NodePort
        httpPort: 8080
        sshPort: 29418

      mode: PRIMARY

      site:
        size: 2Gi

      plugins:
      - name: download-commands
      - name: delete-project

      configFiles:
        gerrit.config: |-
            [index]
              type = LUCENE
            [auth]
              type = DEVELOPMENT_BECOME_ANY_ACCOUNT
            [httpd]
              requestLog = true
              gracefulStopTimeout = 20s
            [user]
              name = Gerrit Code Review
              email = gerrit@example.com
              anonymousCoward = Unnamed User
            [container]
              javaOptions = -Xms200m
              javaOptions = -Xmx4g

        replication.config: |-
            [remote]
              fetch = +refs/*:refs/*
              mirror = true
              timeout = 600
              rescheduleDelay = 15
              replicationDelay = 5
              createMissingRepositories = true
              replicateProjectDeletions = true
              replicateHiddenProjects = true
            [gerrit]
              autoReload = true
              replicateOnStartup = false
            [replication]
              lockErrorMaxRetries = 5
              maxRetries = 5
              useCGitClient = false
              consumeStreamEvents = false
              eventBrokerTopic = gerrit
              syncRefs = "ALL REFS ASYNC"
              maxApiPayloadSize = 40000

      secretRef: gerrit-secure-config
