apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gerrit-slave-configmap
  labels:
    app: gerrit-slave
    chart: {{ template "gerrit-slave.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.gerritSlave.etc.config }}
  {{ $key }}:
{{ toYaml $value | indent 4 }}
  {{- end }}
