apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gerrit-slave-ingress
  labels:
    app: gerrit-slave
    chart: {{ template "gerrit-slave.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{ if .Values.gerritSlave.ingress.additionalAnnotations -}}
  annotations:
{{ toYaml .Values.gerritSlave.ingress.additionalAnnotations  | indent 4 }}
  {{- end }}
spec:
  {{ if .Values.gerritSlave.ingress.tls.enabled -}}
  tls:
  - hosts:
    - {{ .Values.gerritSlave.ingress.host }}
    {{ if .Values.gerritSlave.ingress.tls.secret.create -}}
    secretName: {{ .Release.Name }}-gerrit-slave-tls-secret
    {{- else }}
    secretName: {{ .Values.gerritSlave.ingress.tls.secret.name }}
    {{- end }}
  {{- end }}
  rules:
  - host: {{required "A host URL is required for the Gerrit slave Ingress. Please set 'gerritSlave.ingress.host'" .Values.gerritSlave.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-gerrit-slave-service
          servicePort: {{ .Values.gerritSlave.service.http.port }}
