kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-git-filesystem-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.gitRepositoryStorage.size }}
  storageClassName: {{ .Values.storageClasses.shared.name }}
