---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gerrit
  namespace: gerrit #CHANGE: Change it to the namespace running Gerrit

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gerrit
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gerrit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gerrit
subjects:
- kind: ServiceAccount
  name: gerrit
  namespace: gerrit #CHANGE: Change it to the namespace running Gerrit
