apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit-load-tester
spec:
  replicas: 15
  selector:
    matchLabels:
      app: gerrit-load-tester
  template:
    metadata:
      labels:
        app: gerrit-load-tester
    spec:
      containers:
      - name: gerrit-load-tester
        image: tdraebingdev/loadtest
        args:
        - "-U"
        - "http://master.ingress.chart-test.gitservice.shoot.canary.k8s-hana.ondemand.com"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
