apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-gerrit-secure-config
  labels:
    app: gerrit
    chart: {{ template "gerrit.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{ if .Values.gerrit.keystore -}}
  keystore: {{ .Values.gerrit.keystore }}
  {{- end }}
  secure.config: {{ .Values.gerrit.config.secure | b64enc }}
type: Opaque
---
{{ if and (not .Values.certManager.enabled) .Values.gerrit.ingress.tls.enabled .Values.gerrit.ingress.tls.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-gerrit-tls-secret
  labels:
    app: gerrit
    chart: {{ template "gerrit.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  {{ with .Values.gerrit.ingress.tls.secret -}}
  tls.crt: {{ .cert | b64enc }}
  tls.key: {{ .key | b64enc }}
  {{- end }}
{{- end }}
