apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gerrit-service
  labels:
    app.kubernetes.io/component: gerrit
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: {{ template "gerrit.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  {{ with .Values.gerrit.service }}
  ports:
  - name: http
    port: {{ .http.port }}
    targetPort: 8080
  {{- if .ssh.enabled }}
  - name: ssh
    port: {{ .ssh.port }}
    targetPort: 29418
  {{- end }}
  type: {{ .type }}
  {{- end }}
  selector:
    app.kubernetes.io/component: gerrit
    app.kubernetes.io/instance: {{ .Release.Name }}

