apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-gerrit-secure-config
  labels:
    app: gerrit
    chart: {{ template "gerrit.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{ if .Values.gerrit.keystore -}}
  keystore: {{ .Values.gerrit.keystore }}
  {{- end }}
  {{ if .Values.gerrit.service.ssh.enabled -}}
  ssh_host_rsa_key: {{ .Values.gerrit.service.ssh.rsaKey | b64enc }}
  {{- end }}
  {{- range $key, $value := .Values.gerrit.etc.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
type: Opaque
---
{{ if and .Values.gerrit.ingress.tls.enabled .Values.gerrit.ingress.tls.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-gerrit-tls-secret
  labels:
    app: gerrit
    chart: {{ template "gerrit.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  {{ with .Values.gerrit.ingress.tls.secret -}}
  tls.crt: {{ .cert | b64enc }}
  tls.key: {{ .key | b64enc }}
  {{- end }}
{{- end }}
