apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-gerrit-secure-config
  labels:
    app.kubernetes.io/component: gerrit
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: {{ template "gerrit.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{ if .Values.gerrit.keystore -}}
  keystore: {{ .Values.gerrit.keystore }}
  {{- end }}
  {{- range $key, $value := .Values.gerrit.etc.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
type: Opaque
