{{ if .Values.caCert -}}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-tls-ca
  labels:
    app: gerrit
    chart: {{ template "gerrit.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  ca.crt: {{ .Values.caCert | b64enc }}
type: Opaque
{{- end }}
