#!/bin/ash

if [ "$DISABLE_HTTP" = "true" ] ;then
  rm -f /etc/apache2/conf.d/git-http-backend.conf
fi

if [ "$DISABLE_HTTPS" = "true" ] ;then
  rm -f /etc/apache2/conf.d/git-https-backend.conf
fi

/usr/sbin/apachectl start \
  && tail -F -q -n +1 /var/log/apache2/*.log
