#!/bin/bash

if [ "$DISABLE_HTTP" = "true" ] ;then
  rm /etc/apache2/sites-enabled/git-http-backend.conf
fi

if [ "$DISABLE_HTTPS" = "true" ] ;then
  rm /etc/apache2/sites-enabled/git-https-backend.conf
fi

/etc/init.d/apache2 start \
  && tail -F -q -n +1 /var/log/apache2/*.log
