apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gerrit-replica-service
  labels:
    app.kubernetes.io/component: gerrit-replica
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: {{ template "gerrit-replica.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.gerritReplica.service.additionalAnnotations }}
  annotations:
{{ toYaml .Values.gerritReplica.service.additionalAnnotations  | indent 4 }}
  {{- end }}
spec:
  {{ with .Values.gerritReplica.service }}
  ports:
  - name: http
    port: {{ .http.port }}
    targetPort: 8080
  {{ if .ssh.enabled -}}
  - name: ssh
    port: {{ .ssh.port }}
    targetPort: 29418
  {{- end }}
  type: {{ .type }}
  externalTrafficPolicy: {{ .externalTrafficPolicy }}
  {{- end }}
  selector:
    app.kubernetes.io/component: gerrit-replica
    app.kubernetes.io/instance: {{ .Release.Name }}
