apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-gerrit-replica-secure-config
  labels:
    app: gerrit-replica
    chart: {{ template "gerrit-replica.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{ if .Values.gerritReplica.keystore -}}
  keystore: {{ .Values.gerritReplica.keystore }}
  {{- end }}
  {{- range $key, $value := .Values.gerritReplica.etc.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
type: Opaque
