apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-gerrit-replica-secure-config
  labels:
    app: gerrit-replica
    chart: {{ template "gerrit-replica.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{ if .Values.gerritReplica.keystore -}}
  keystore: {{ .Values.gerritReplica.keystore }}
  {{- end }}
  secure.config: {{ .Values.gerritReplica.config.secure | b64enc }}
type: Opaque
---
{{ if and .Values.gerritReplica.ingress.tls.enabled (not .Values.istio.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-gerrit-replica-tls-secret
  labels:
    app: gerrit-replica
    chart: {{ template "gerrit-replica.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  {{ with .Values.gerritReplica.ingress.tls -}}
  tls.crt: {{ .cert | b64enc }}
  tls.key: {{ .key | b64enc }}
  {{- end }}
{{- end }}
