{{- $root := . -}}

apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-gerrit-replica-secure-config
  labels:
    app: gerrit-replica
    chart: {{ template "gerrit-replica.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{ if .Values.gerritReplica.keystore -}}
  keystore: {{ .Values.gerritReplica.keystore }}
  {{- end }}
  {{ if .Values.gerritReplica.service.ssh.enabled -}}
  ssh_host_rsa_key: {{ .Values.gerritReplica.service.ssh.rsaKey | b64enc }}
  {{- end }}
  {{- range $key, $value := .Values.gerritReplica.etc.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
type: Opaque
{{- range .Values.gerritReplica.additionalSecrets -}}
{{- if .data }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ $root.Release.Name }}-{{ .name }}
  labels:
    app: gerrit-replica
    chart: {{ template "gerrit-replica.chart" $root }}
    heritage: {{ $root.Release.Service }}
    release: {{ $root.Release.Name }}
data:
{{ toYaml .data | indent 2 }}
{{- end }}
{{- end }}
