apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gerrit-replica-service
  labels:
    app: gerrit-replica
    chart: {{ template "gerrit-replica.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  {{ with .Values.gerritReplica.service }}
  ports:
  - name: http
    port: {{ .http.port }}
    targetPort: 8080
  {{ if .ssh.enabled -}}
  - name: ssh
    port: {{ .ssh.port }}
    targetPort: 29418
  {{- end }}
  selector:
    app: gerrit-replica
  type: {{ .type }}
  externalTrafficPolicy: {{ .externalTrafficPolicy }}
  {{- end }}
