apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-git-backend-service
  labels:
    app.kubernetes.io/component: git-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: {{ template "gerrit-replica.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  {{ with .Values.gitBackend.service }}
  ports:
  - name: http
    port: {{ .http.port }}
    targetPort: 80
  selector:
    app.kubernetes.io/component: git-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .type }}
  {{- end }}
