apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-git-backend-secret
  labels:
    app: git-backend
    chart: {{ template "gerrit-replica.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  .htpasswd: {{ required "A .htpasswd-file is required for the git backend." .Values.gitBackend.credentials.htpasswd | b64enc }}
type: Opaque
---
{{ if and .Values.gitBackend.tls.secret.create (or .Values.gitBackend.ingress.tls.enabled .Values.gitBackend.service.https.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-git-backend-tls-secret
  labels:
    app: git-backend
    chart: {{ template "gerrit-replica.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  {{ with .Values.gitBackend.tls -}}
  tls.crt: {{ .cert | b64enc }}
  tls.key: {{ .key | b64enc }}
  {{- end }}
{{- end }}
