{{ if .Values.promtailSidecar.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-promtail-secret
  labels:
    app: gerrit-replica
    chart: {{ template "gerrit-replica.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  promtail.secret: {{ .Values.promtailSidecar.loki.password | b64enc }}
  {{- if not .Values.promtailSidecar.tls.skipVerify }}
  promtail.ca.crt: {{ .Values.promtailSidecar.tls.caCert | b64enc }}
  {{- end }}
{{- end }}
