#!/bin/bash

gerrit_uid=$(id -u)
gerrit_gid=$(cut -d: -f3 < <(getent group users))

for dir in /var/gerrit/*; do
  /var/tools/validate_site.sh $dir $gerrit_uid $gerrit_gid || exit 1
done

/var/gerrit/bin/gerrit.sh check >/dev/null
if [[ $? -eq 1 ]]; then
    echo "Performing Gerrit site initialization..."
    java -jar /var/gerrit/bin/gerrit.war init \
        --batch \
        -d /var/gerrit
fi

java -jar /var/gerrit/bin/gerrit.war reindex \
    -d /var/gerrit

git config -f /var/gerrit/etc/gerrit.config --add \
    container.javaOptions "-Djava.security.egd=file:/dev/./urandom"

/var/gerrit/bin/gerrit.sh start

tail -F -n +1 /var/gerrit/logs/{error,httpd,sshd}_log
