#!/bin/bash

symlink_config_to_site(){
    mkdir -p /var/gerrit/etc
    for file in keystore gerrit.config secure.config replication.config; do
        test -f /var/config/$file && \
            ln -sf /var/config/$file /var/gerrit/etc/$file
    done
}

# Ensure that configuration provided at /var/config is symlinked to the Gerrit
# site. This is necessary, because mounting files from secrets/configmaps in
# Kubernetes make the containing directory read-only.
symlink_config_to_site

java -jar /var/war/gerrit.war init \
    --batch \
    --install-plugin replication \
    --install-plugin commit-message-length-validator \
    --install-plugin download-commands \
    --install-plugin reviewnotes \
    -d /var/gerrit

symlink_config_to_site

java -jar /var/gerrit/bin/gerrit.war reindex \
    -d /var/gerrit

/var/gerrit/bin/gerrit.sh start
tail -F -n +1 /var/gerrit/logs/{error,httpd,sshd}_log
