apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  ports:
  - name: status-port
    port: 15021
    targetPort: 15021
  - name: http2
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  - name: ssh
    port: 29418
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  type: LoadBalancer
  # MODIFIED: loadBalancerIP should be set to ensure a stable IP address
  # TO_BE_CHANGED: Change IP
  loadBalancerIP: xxx.xxx.xxx.xxx
