# MODIFIED: This secret was added manually, but is required to access kiali
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  # TO_BE_CHANGED: Change credentials
  username: YWRtaW4=
  passphrase: c2VjcmV0
