image:
  registry: docker.io
  org: k8sgerrit
  name: gerrit-operator
  tag: latest
  imagePullPolicy: Always
  imagePullSecrets: []
  # - name: my-secret-1

## Required to use an external/persistent keystore, otherwise a keystore using
## self-signed certificates will be generated
externalKeyStore:
  enabled: false
  # base64-encoded Java keystore
  jks: ""
  # Java keystore password (not base64-encoded)
  password: ""
