#!/bin/bash

# Copyright (C) 2024 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT_PATH="$(dirname "$(readlink -f "$0")")"

CHART_TEMPLATE_PATH="$SCRIPT_PATH/../../helm-charts/gerrit-operator-crds/templates"
CURRENT_CRD_PATH="$SCRIPT_PATH/../../crd/current"

rm -rf $CHART_TEMPLATE_PATH
cp -R $CURRENT_CRD_PATH $CHART_TEMPLATE_PATH

for f in "$CHART_TEMPLATE_PATH/"*.yml; do
  chmod 666 $f
  OLD_CRD_PATH="$SCRIPT_PATH/../../crd/deprecated/$(basename "$f")"
  OLD_VERSION="$(yq -e '.spec.versions.[0]' "$OLD_CRD_PATH")" \
    yq -i '.spec.versions += env(OLD_VERSION)' "$f"
done
