#!/bin/bash -x

usage() {
    me=`basename "$0"`
    echo >&2 "Usage: $me [--help] [--delete DELETE_VERSION] OLD NEW"
    exit 1
}

while test $# -gt 0 ; do
  case "$1" in
  --help)
    usage
    ;;

  --delete)
    shift
    DELETE_VERSION=$1
    shift
    ;;

  *)
    break
  esac
done

OLD="$1"
shift
NEW="$1"

if test -z "$OLD" || test -z "$NEW"; then
    usage
fi

SCRIPT_PATH="$(dirname "$(readlink -f "$0")")"
API_PATH="$SCRIPT_PATH/../src/main/java/com/google/gerrit/k8s/operator"

# Copy old version
cp -R "$API_PATH/$OLD" "$API_PATH/$NEW"

# Adapt references to use new version
find $SCRIPT_PATH/../src \
    -path "$SCRIPT_PATH/../src/main/java/com/google/gerrit/k8s/operator/$OLD" \
    -prune \
    -o \
    -type f \
    -exec sed -i '' "s/com.google.gerrit.k8s.operator.$OLD/com.google.gerrit.k8s.operator.$NEW/g" {} ';'

if test -n "$DELETE_VERSION"; then
  sed -i '' "s/$DELETE_VERSION/$NEW/g" "$SCRIPT_PATH/../src/main/java/com/google/gerrit/k8s/operator/Constants.java"
else
  sed -i '' "s/\"$OLD\"/\"$OLD\", \"$NEW\"/g" "$SCRIPT_PATH/../src/main/java/com/google/gerrit/k8s/operator/Constants.java"
fi

find $SCRIPT_PATH/.. \
    -name '*.yaml' \
    -type f \
    -exec sed -i '' "s#gerritoperator.google.com/$OLD#agerritoperator.google.com/$NEW#g" {} ';'

find $SCRIPT_PATH/../src/main/java/com/google/gerrit/k8s/operator/$NEW \
    -type f \
    -exec sed -i '' "s/@Version(\"$OLD\")/@Version(\"$NEW\")/g" {} ';'

find $SCRIPT_PATH/../src/main/java/com/google/gerrit/k8s/operator/$OLD \
    -type f \
    -exec sed -i '' "s/@Version(\"$OLD\")/@Version(value = \"$OLD\", storage = false)/g" {} ';'

find $SCRIPT_PATH/../src/main/java/com/google/gerrit/k8s/operator/$OLD \
    -type f \
    -exec sed -i '' "s/public class/@Deprecated\npublic class/g" {} ';'

if test -n "$DELETE_VERSION"; then
    rm -rf $SCRIPT_PATH/../src/main/java/com/google/gerrit/k8s/operator/$DELETE_VERSION
fi
