#!/bin/bash

usage() {
    me=`basename "$0"`
    echo >&2 "Usage: $me [--help] [--osx] NEW"
    exit 1
}

while test $# -gt 0 ; do
  case "$1" in
  --help)
    usage
    ;;

  --osx)
    shift
    export BACKUP_EXT=""
    ;;

  *)
    break
  esac
done

NEW="$1"

if test -z "$NEW"; then
    usage
fi

SCRIPT_PATH="$(dirname "$(readlink -f "$0")")"
API_PATH="$SCRIPT_PATH/../src/main/java/com/google/gerrit/k8s/operator"

OLD="$(yq e '.spec.versions[0].name' $SCRIPT_PATH/../../crd/current/gerritclusters.gerritoperator.google.com-v1.yml)"

sed -i ${BACKUP_EXT+"$BACKUP_EXT"} "s/$OLD/$NEW/g" "$API_PATH/Constants.java"

find $SCRIPT_PATH/.. \
    -name '*.yaml' \
    -type f \
    -exec sed -i ${BACKUP_EXT+"$BACKUP_EXT"} "s#gerritoperator.google.com/$OLD#gerritoperator.google.com/$NEW#g" {} ';'

sed -i ${BACKUP_EXT+"$BACKUP_EXT"} "s#$OLD#$NEW#g" $SCRIPT_PATH/../../Documentation/operator-api-reference.md

rm -r $SCRIPT_PATH/../../crd/deprecated
mv $SCRIPT_PATH/../../crd/current $SCRIPT_PATH/../../crd/deprecated
for f in "$SCRIPT_PATH/../../crd/deprecated/"*.yml; do
  yq -i '.spec.versions[0].storage = false' "$f"
done
mkdir $SCRIPT_PATH/../../crd/current

pushd $SCRIPT_PATH/..
  mvn clean install
popd
