storageClasses:
  default:
    name: standard
  shared:
    name: shared-storage

database:
  provider: mysql
  replication:
    enabled: true
    mysql:
      config:
        masterHost: gerrit-master-mysql
        masterPort: 3306
        masterUser: repl
        masterPassword: password
        masterLogFile: mysql-bin.000004
        masterLogPos: 446
      dbDumpAcceptPath: /var/data/db/master_dump.sql

gitBackend:
  resources:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 100Mi

  logging:
    persistence:
      enabled: false

  service:
    type: NodePort

  ingress:
    enabled: true
    host: backend.gerrit

gitGC:
  schedule: "*/5 * * * *"

  resources:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 100Mi

  logging:
    persistence:
      enabled: false

gerritSlave:
  initializeTestSite:
    enabled: false

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi


  logging:
    persistence:
      enabled: false

  ingress:
    host: slave.gerrit

  keystore: /u3+7QAAAAIAAAABAAAAAQAFamV0dHkAAAFnT7a0wgAABQIwggT+MA4GCisGAQQBKgIRAQEFAASCBOoAKuHk7AkpPJjC9d79I9a7GUIsevJtObajyULChiEPCnUKAtzn3wiTOznG9spsBlT9nEBQI7n0FDUjx7NxDS7fMHPVi/R67PGVe5LgStbMdSaV5MtW2rPsbKIAYV84krwRHqHrGM4VBXhjtrJwucquccmlZwRNjImbYI3vtjo7F/wSxW7kHrVhHmeHgkV9q63RWuBxe3Vz89Oek8/ovgx10rYjLQdQwHE5ZJUU4BgqrE/1cqcv7MTO+8p0ooKb3ziuwWJdO96bF42KrKnIX/1AZ3IntU/JIEkm2yTocqdW7kgLgE+6Tzpyi2AmtFC6ka+phZU4jr4N0ob4CjhL2rXpTSxcv7nvzoDJBbUHfgzHpobXdkyPmu2WLCOGNLZ+cXyg1PeHzJgm44Q06lXK6Nnr4cXKje7YAyM7cgmB1ejRuEFfWbDSLi5+4wfhjsKTUcP5WUADaBaXMxsqNvStKFgdfL0xXmYBFKPhv3PFw5ekgThmYhIYE1lUFLKGWvijIaisPuMVsdu7aRQThgc2oX8J9JUMaYef7dGFUT7ZK/7ie2bRXIjCxSRR8Ppr2KeBwrutChvaYrhi2oQ1VqEm2XDF71g3foCsPfTxdkcvWCo3MXvi4po968sNsospXrU9loalmp+lYSuPgO32Nc/z7JlKZOqm8+nqgGXAMJ76MnA9esaFdds2bIELPjra2xVRNtiClmeWYfzqv3raHTCpe4SOkqT9ds/hmIrERo17DZU1VlXtmmA1RhZj8KAYyLpKZwJoNrQ87sQnLNLNSztWMfwrbJXOlKaVwcIoxfJBU2DZfaNuTQJQt/7GcGIdpzoqfgFNWbT4PvllL0d5DEKrX932a8oY1T9uhahXUiCOTQc3a3kaM4bIPwi9PjCLdJNqny/W10TJPJ52SF3b/IxGmtToDerBDCh3x+bmoEpT6RvQXujHNV2jH0WZXMjLMgUr8GHRVO36skSE3Vp0AN9vClUeC4A06tkEeQiPzuhYqt202D+cHBXoOM+eZSuFqhTY72zbuQbMyTsUxTKCKGzMyr0Dyup9g6GOV9/Glj1ekwTHya4bALQbsZTjQCWHjNWp2QSuvELwV+4Zq/P/8gkf2+ZSMyV/fjsQtBvwwEX27uKdsACqAlKmwiXweySE9iGiTN+1TDMFUHyyVXwGAtp7XVoZ6rjm64ZinpObMx56esF2izC16PY4eK3w2YuNrj2iCt0GPrpglVj3PXl33NkPtGwe3aRFMuuSaV1iWploN5fefSjuwnmSIOgi5vJiYssp9DynE7/EC7LOxDHWOFeB5QSKwsSpKLNWXCwrvZiDVuaphRthZc6S7BUXZ+1rs6RxMq3gbQk/rhN+v7sjtfCSj7tJKrx7eT2a7ecYcAThfzMlEA8MDSbJjj5MgO7UOTE0VEE1JmHBts6lF/ZT26rxbZacOhA2pLWRPVsmbRg3FRl/idAR8QswsLMEo4AUvC6JhNlIWnDcjlBukET/zXKzyoeGR3jk8Ftb6/d2f62f0Pk29b4Gf2fgaeZDLY9JnVkATNvZxYi5OH2bfnPpYfMqRU9rv2L8B9EOz8ktUq8gSa5T1uyErTfln25uSM9l4Ayd+mCuLoT6iYsBrrkNL0RbkK4d+wC7tMwrXy+wuIfuSivoCDn7JJ8f8eudYIxWih4urK3npNdwX/OVPcFfAAAAAQAFWC41MDkAAAN1MIIDcTCCAlmgAwIBAgIEein74jANBgkqhkiG9w0BAQsFADBpMRAwDgYDVQQGEwdVbmtub3duMRAwDgYDVQQIEwdVbmtub3duMRAwDgYDVQQHEwdVbmtub3duMQ8wDQYDVQQKEwZHZXJyaXQxDzANBgNVBAsTBkdlcnJpdDEPMA0GA1UEAxMGR2Vycml0MB4XDTE4MTEyNjExMTAzMFoXDTE5MDIyNDExMTAzMFowaTEQMA4GA1UEBhMHVW5rbm93bjEQMA4GA1UECBMHVW5rbm93bjEQMA4GA1UEBxMHVW5rbm93bjEPMA0GA1UEChMGR2Vycml0MQ8wDQYDVQQLEwZHZXJyaXQxDzANBgNVBAMTBkdlcnJpdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKcb1vnLTcFlZu+XEZ0W2OxV6zfQwv2HV6/bSdbyPu7MxljUF9WKxtlGfzdbgWgDFL5hjgzUeCc1Kxhkg5yaXyT0/mX7Bx5nWsBygRmQ9BBJHjwf0/wm3ER6wdo4mW1vNbeD75yjT14iUw2vJPUjTftELADwiV9kPGlYWMEsoho0wf5sX4Eb+X0Rxv0tefNclo85wZyubzpYDvdlp4IJMry1cpj6H+hsR+TsJbeM3IJweST5jsSD7zSiLTGWW4QIRM4k7Ez8BvC2tB7Py1HU/X0o8Tlh25C18buzejM4GoMj3zCcdYqmTP3z5Abgjv++d4FoiNA3obLwjhapv5GTg0UCAwEAAaMhMB8wHQYDVR0OBBYEFOXnmR0YjrjY/832n8c2yC5SVm6cMA0GCSqGSIb3DQEBCwUAA4IBAQAMZ1CdiTIWiZjZVbkKd2b9o4e8WAI7eLlUfgzU0pVP6FvUDs7jfkBIDxnOlicrnubDWlaQdNcJWo/ZmwrdXkc8crLWqrB/lLOKCASg3/1v3Z2Z1Njb8ozvAoKgtnDpBasBjfGFKA0xKajjjmMtoHqvTpqbPlKRFvvogpT7eaeRKVet3IISmNQZSdU0m8I0VKfrsUOb+wTwbdDDKnxmC9DGxePI53ORVLrpdRkqXJ502mr5rmILEnIdT2xNOJrKBm6t+uhOO9wjp9diAVdrS/ygXNt+NcXRJ6bszOj1nSjFbh9KSJq7luRnohA+jBefv4HKIb4ljmmfZzm+YZkizkuX0D/EhQj1EbN2dk55qMlVOafnqXQ=

  config:
    gerrit: |-
      [gerrit]
        basePath = git
        serverId = gerrit-slave-1
        canonicalWebUrl = http://slave.gerrit
      [database]
        type = mysql
        hostname = gerrit-slave-mysql
        port = 33306
        database = reviewdb
        url = jdbc:mysql://gerrit-slave-mysql:33306/reviewdb?nullNamePatternMatchesAll=true&useSSL=false
      [index]
        type = LUCENE
      [auth]
        type = DEVELOPMENT_BECOME_ANY_ACCOUNT
      [httpd]
        listenUrl = proxy-http://*:8080/
      [transfer]
        timeout = 120 s
      [user]
        name = Gerrit Code Review
        email = gerrit@example.com
        anonymousCoward = Unnamed User
      [cache]
        directory = cache
      [container]
        user = gerrit
        slave = true
        javaHome = /usr/lib/jvm/java-8-openjdk-amd64
        javaOptions = -Djavax.net.ssl.trustStore=/var/gerrit/etc/keystore
        javaOptions = -Xms50m
        javaOptions = -Xmx1g

    secure: |-
      [database]
        username = gerrit
        password = secret

      [httpd]
        sslKeyPassword = gerrit


mysql:
  enabled: true

  mysqlRootPassword: big_secret
  mysqlUser: gerrit
  mysqlPassword: secret

  persistence:
    enabled: false

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

  service:
    port: 33306
