storageClasses:
  default:
    name: standard
  shared:
    name: shared-storage

gitGC:
  schedule: "*/15 * * * *"

  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 50m
      memory: 100Mi

  logging:
    persistence:
      enabled: false

gerrit:

  resources:
    requests:
      cpu: 200m
      memory: 400Mi
    limits:
      cpu: 500m
      memory: 400Mi

  persistence:
    enabled: false

  livenessProbe:
    initialDelaySeconds: 90
    periodSeconds: 5

  ingress:
    host: primary.gerrit

  config:
    gerrit: |-
      [gerrit]
        basePath = git
        serverId = gerrit-1
        canonicalWebUrl = http://primary.gerrit
      [index]
        type = LUCENE
      [auth]
        type = DEVELOPMENT_BECOME_ANY_ACCOUNT
      [httpd]
        listenUrl = proxy-http://*:8080/
      [sshd]
        listenAddress = off
      [transfer]
        timeout = 120 s
      [user]
        name = Gerrit Code Review
        email = gerrit@example.com
        anonymousCoward = Unnamed User
      [cache]
        directory = cache
      [container]
        user = gerrit
        javaHome = /usr/lib/jvm/java-11-openjdk-amd64
        javaOptions = -Djavax.net.ssl.trustStore=/var/gerrit/etc/keystore
        javaOptions = -Xms300m
        javaOptions = -Xmx300m

    secure: |-
      [remote "replica"]
        username = git
        password = secret

    replication: |-
      [gerrit]
        autoReload = false
        replicateOnStartup = true
        defaultForceUpdate = true

      [remote "replica"]
        url = http://gerrit-replica-git-backend-service/git/${name}.git
        replicationDelay = 0
        timeout = 30
