storageClasses:
  default:
    name: standard
  shared:
    name: shared-storage

nfsWorkaround:
  enabled: true
  chownOnStartup: true

ingress:
  enabled: true
  host: primary.gerrit
  maxBodySize: 50m
  additionalAnnotations:
    kubernetes.io/ingress.class: nginx
  tls:
    enabled: false

gitGC:
  schedule: "*/15 * * * *"

  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 50m
      memory: 100Mi

  logging:
    persistence:
      enabled: false

gerrit:
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 3Gi

  persistence:
    enabled: false

  livenessProbe:
    initialDelaySeconds: 90
    periodSeconds: 15

  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15

  startupProbe:
    initialDelaySeconds: 30
    periodSeconds: 30

  etc:
    config:
      gerrit.config: |-
        [gerrit]
          basePath = git
          serverId = gerrit-1
          canonicalWebUrl = http://primary.gerrit
        [index]
          type = LUCENE
        [auth]
          type = DEVELOPMENT_BECOME_ANY_ACCOUNT
        [httpd]
          listenUrl = proxy-http://*:8080/
        [sshd]
          listenAddress = off
        [transfer]
          timeout = 120 s
        [user]
          name = Gerrit Code Review
          email = gerrit@example.com
          anonymousCoward = Unnamed User
        [cache]
          directory = cache
        [container]
          user = gerrit
          javaHome = /usr/lib/jvm/java-11-openjdk
          javaOptions = -Djavax.net.ssl.trustStore=/var/gerrit/etc/keystore
          javaOptions = -Xms2g
          javaOptions = -Xmx2g

      healthcheck.config: |-
          [healthcheck "auth"]
            enabled = false
          [healthcheck "querychanges"]
            enabled = false
          [healthcheck "activeworkers"]
            enabled = false

      replication.config: |-
        [gerrit]
          autoReload = false
          replicateOnStartup = true
          defaultForceUpdate = true

        [remote "replica"]
          url = http://gerrit-replica-git-backend-service/git/${name}.git
          replicationDelay = 0
          timeout = 30

    secret:
      secure.config: |-
        [remote "replica"]
          username = git
          password = secret
