storageClasses:
  default:
    name: standard
  shared:
    name: shared-storage

gitBackend:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 100Mi

  logging:
    persistence:
      enabled: false

  service:
    type: NodePort

  ingress:
    enabled: true
    host: backend.gerrit

gitGC:
  schedule: "*/15 * * * *"

  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 50m
      memory: 100Mi

  logging:
    persistence:
      enabled: false

gerritReplica:
  initializeTestSite:
    enabled: true

  resources:
    requests:
      cpu: 200m
      memory: 400Mi
    limits:
      cpu: 500m
      memory: 400Mi

  persistence:
    enabled: false

  ingress:
    host: replica.gerrit

  config:
    gerrit: |-
      [gerrit]
        basePath = git
        serverId = gerrit-replica-1
        canonicalWebUrl = http://replica.gerrit
      [index]
        type = LUCENE
      [auth]
        type = DEVELOPMENT_BECOME_ANY_ACCOUNT
      [httpd]
        listenUrl = proxy-http://*:8080/
      [sshd]
        listenAddress = off
      [transfer]
        timeout = 120 s
      [user]
        name = Gerrit Code Review
        email = gerrit@example.com
        anonymousCoward = Unnamed User
      [cache]
        directory = cache
      [container]
        user = gerrit
        replica = true
        javaHome = /usr/lib/jvm/java-11-openjdk-amd64
        javaOptions = -Djavax.net.ssl.trustStore=/var/gerrit/etc/keystore
        javaOptions = -Xms300m
        javaOptions = -Xmx300m
