#!/bin/bash

create_missing_repository(){
  test -d $1 || git init --bare $1
}

gerrit_uid=$(id -u)
gerrit_gid=$(cut -d: -f3 < <(getent group users))

for dir in /var/gerrit/*; do
  /var/tools/validate_site.sh $dir $gerrit_uid $gerrit_gid || exit 1
done

JAVA_OPTIONS=$(git config --file /var/gerrit/etc/gerrit.config --get-all container.javaOptions)
git config -f /var/gerrit/etc/gerrit.config container.slave true

create_missing_repository /var/gerrit/git/All-Projects.git
create_missing_repository /var/gerrit/git/All-Users.git

# workaround gerrit.sh does not start httpd
java ${JAVA_OPTIONS} -jar /var/gerrit/bin/gerrit.war daemon \
    -d /var/gerrit \
    --enable-httpd \
    --slave &

tail -F -n +1 /var/gerrit/logs/{error,httpd,sshd}_log
