apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gerrit-master-configmap
  labels:
    app: gerrit-master
    chart: {{ template "gerrit-master.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.gerritMaster.etc.config }}
  {{ $key }}:
{{ toYaml $value | indent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gerrit-init-configmap
  labels:
    app: gerrit-master
    chart: {{ template "gerrit-master.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  gerrit-init.yaml: |-
    pluginCache: {{ .Values.gerritMaster.plugins.cache.enabled }}
    pluginCacheDir: /var/mnt/plugins
    {{- if .Values.gerritMaster.plugins.packaged }}
    packagedPlugins:
{{ toYaml .Values.gerritMaster.plugins.packaged | indent 6}}
    {{- end }}
    {{- if .Values.gerritMaster.plugins.downloaded }}
    downloadedPlugins:
{{ toYaml .Values.gerritMaster.plugins.downloaded | indent 6 }}
    {{- end }}
