apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-gerrit-master-stateful-set
  labels:
    app: gerrit-master
    chart: {{ template "gerrit-master.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}-gerrit-master-service
  replicas: {{ .Values.gerritMaster.replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.gerritMaster.maxSurge }}
      maxUnavailable: {{ .Values.gerritMaster.maxUnavailable }}
  selector:
    matchLabels:
      app: gerrit-master
  template:
    metadata:
      labels:
        app: gerrit-master
    spec:
      securityContext:
        fsGroup: 100
      {{ if .Values.images.registry.ImagePullSecret.name -}}
      imagePullSecrets:
      - name: {{ .Values.images.registry.ImagePullSecret.name }}
      {{- end }}
      initContainers:
      - name: site-cleanup
        image: busybox
        securityContext:
          runAsUser: 1000
          runAsGroup: 100
        command:
        - sh
        - -c
        args:
        - |
          # Remove directories that should be mounted rather than exist with the
          # rest of the site
          for dir in git {{ if eq .Values.gerritMaster.index.type "elasticsearch" }}index{{ end }}; do
            [ ! -L /var/gerrit/$dir ] && rm -rf /var/gerrit/$dir
          done
          rm -f /var/gerrit/logs/gerrit.pid
        volumeMounts:
        - name: gerrit-site
          mountPath: "/var/gerrit"
      - name: gerrit-init
        image: {{ template "registry" . }}{{ .Values.gerritMaster.images.gerritInit }}:{{ .Values.images.version }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        command:
        - /bin/bash
        - -ce
        args:
        - |
          symlink_config_to_site(){
            {{ if .Values.gerritMaster.keystore -}}
            ln -s /var/config/keystore /var/gerrit/etc/keystore
            {{- end }}
            ln -sf /var/config/gerrit.config /var/gerrit/etc/gerrit.config
            ln -sf /var/config/secure.config /var/gerrit/etc/secure.config
          }

          mkdir -p /var/gerrit/etc
          symlink_config_to_site

          for dir in git {{ if eq .Values.gerritMaster.index.type "elasticsearch" }}index{{ end }}; do
            if [ ! -d /var/gerrit/$dir ]; then
              ln -sf /var/mnt/$dir /var/gerrit/
            fi
          done

          /var/tools/gerrit_init.py \
            {{- if .Values.gerritMaster.reviewdb.enabled }}
            --reviewdb \
            {{- end }}
            -s /var/gerrit \
            -p replication \
            -p commit-message-length-validator \
            -p download-commands \
            -p reviewnotes

          symlink_config_to_site

          /var/tools/validate_db.py -s /var/gerrit

          {{ if not .Values.gerritMaster.persistence.enabled -}}
            FLAGS="$FLAGS --force"
          {{- end }}

          # TODO (Thomas): Do not enforce offline-reindexing, when online-reindexing
          # is configured.
          /var/tools/gerrit_reindex.py $FLAGS \
            -s /var/gerrit
        volumeMounts:
        - name: gerrit-site
          mountPath: "/var/gerrit"
        - name: git-filesystem
          mountPath: "/var/mnt/git"
        {{ if eq .Values.gerritMaster.index.type "elasticsearch" -}}
        - name: gerrit-index-config
          mountPath: "/var/mnt/index"
        {{- end }}
        - name: gerrit-config
          mountPath: "/var/config/gerrit.config"
          subPath: gerrit.config
        - name: gerrit-master-secure-config
          mountPath: "/var/config/secure.config"
          subPath: secure.config
        {{ if .Values.gerritMaster.keystore -}}
        - name: gerrit-master-secure-config
          mountPath: "/var/config/keystore"
          subPath: keystore
        {{- end }}
      containers:
      - name: gerrit-master
        image: {{ template "registry" . }}{{ .Values.gerritMaster.images.gerritMaster }}:{{ .Values.images.version }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        ports:
        - name: gerrit-port
          containerPort: 8080
        volumeMounts:
        - name: gerrit-site
          mountPath: "/var/gerrit"
        - name: git-filesystem
          mountPath: "/var/mnt/git"
        {{ if eq .Values.gerritMaster.index.type "elasticsearch" -}}
        - name: gerrit-index-config
          mountPath: "/var/mnt/index"
        {{- end }}
        - name: gerrit-config
          mountPath: "/var/config/gerrit.config"
          subPath: gerrit.config
        - name: gerrit-config
          mountPath: "/var/config/replication.config"
          subPath: replication.config
        - name: gerrit-master-secure-config
          mountPath: "/var/config/secure.config"
          subPath: secure.config
        {{ if .Values.gerritMaster.keystore -}}
        - name: gerrit-master-secure-config
          mountPath: "/var/config/keystore"
          subPath: keystore
        {{- end }}
        resources:
{{ toYaml .Values.gerritMaster.resources | indent 10 }}
        livenessProbe:
          httpGet:
            path: /config/server/version
            port: gerrit-port
{{ toYaml .Values.gerritMaster.livenessProbe | indent 10 }}
        readinessProbe:
          httpGet:
            path: /config/server/version
            port: gerrit-port
{{ toYaml .Values.gerritMaster.readinessProbe | indent 10 }}
      volumes:
      {{ if not .Values.gerritMaster.persistence.enabled -}}
      - name: gerrit-site
        emptyDir: {}
      {{- end }}
      - name: git-filesystem
        persistentVolumeClaim:
          {{- if .Values.gitRepositoryStorage.externalPVC.use }}
          claimName: {{ .Values.gitRepositoryStorage.externalPVC.name }}
          {{- else }}
          claimName: {{ .Release.Name }}-git-filesystem-pvc
          {{- end }}
      {{ if eq .Values.gerritMaster.index.type "elasticsearch" -}}
      - name: gerrit-index-config
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-gerrit-index-config-pvc
      {{- end }}
      - name: gerrit-config
        configMap:
          name: {{ .Release.Name }}-gerrit-master-configmap
      - name: gerrit-master-secure-config
        secret:
          secretName: {{ .Release.Name }}-gerrit-master-secure-config
  volumeClaimTemplates:
  {{ if .Values.gerritMaster.persistence.enabled -}}
  - metadata:
      name: gerrit-site
      labels:
        app: gerrit-master
        chart: {{ template "gerrit-master.chart" . }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.gerritMaster.persistence.size }}
      storageClassName: {{ .Values.storageClasses.default.name }}
  {{- end }}
