apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-gerrit-master-secure-config
  labels:
    app: gerrit-master
    chart: {{ template "gerrit-master.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{ if .Values.gerritMaster.keystore -}}
  keystore: {{ .Values.gerritMaster.keystore }}
  {{- end }}
  secure.config: {{ .Values.gerritMaster.config.secure | b64enc }}
type: Opaque
---
{{ if and .Values.gerritMaster.ingress.tls.enabled .Values.gerritMaster.ingress.tls.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-gerrit-master-tls-secret
  labels:
    app: gerrit-master
    chart: {{ template "gerrit-master.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  {{ with .Values.gerritMaster.ingress.tls.secret -}}
  tls.crt: {{ .cert | b64enc }}
  tls.key: {{ .key | b64enc }}
  {{- end }}
{{- end }}
